### ISSUE TITLE
Is this still active

### ISSUE THREAD

**Issue by frink** [BramGiesen/cv-lfo-blender-lv2#3]
This looks awesome but it looks like it's abandoned from the README having a list of TODOs and no commits in 3 years. Have plans changed on this. Is there still active development?

**Comment by BramGiesen** [comment]
Hi @frink, at this moment I don't have any concrete plans for continuing with this, although I might pick it up again in the future.

**Comment by frink** [comment]
thanks I'll fork it and send you a PR if I do anything drastic
